# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anatomy_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnatomyViewer(object):
    def setupUi(self, AnatomyViewer):
        AnatomyViewer.setObjectName("AnatomyViewer")
        AnatomyViewer.resize(1570, 1080)
        AnatomyViewer.setMinimumSize(QtCore.QSize(1570, 1080))
        AnatomyViewer.setMaximumSize(QtCore.QSize(1570, 1080))
        AnatomyViewer.setAcceptDrops(False)
        AnatomyViewer.setWindowOpacity(1.0)
        AnatomyViewer.setAutoFillBackground(True)
        AnatomyViewer.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralWidget = QtWidgets.QWidget(AnatomyViewer)
        self.centralWidget.setObjectName("centralWidget")
        self.sliderSliceIndex = QtWidgets.QSlider(self.centralWidget)
        self.sliderSliceIndex.setGeometry(QtCore.QRect(30, 570, 191, 22))
        self.sliderSliceIndex.setMaximum(512)
        self.sliderSliceIndex.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSliceIndex.setObjectName("sliderSliceIndex")
        self.graphicsViewImage = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsViewImage.setGeometry(QtCore.QRect(10, 10, 512, 512))
        self.graphicsViewImage.setObjectName("graphicsViewImage")
        self.graphicsViewLabel = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsViewLabel.setGeometry(QtCore.QRect(530, 10, 512, 512))
        self.graphicsViewLabel.setObjectName("graphicsViewLabel")
        self.graphicsViewLabelOverlay = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsViewLabelOverlay.setGeometry(QtCore.QRect(1050, 10, 512, 512))
        self.graphicsViewLabelOverlay.setObjectName("graphicsViewLabelOverlay")
        self.doubleSpinBoxImageWindow = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBoxImageWindow.setGeometry(QtCore.QRect(288, 532, 81, 20))
        self.doubleSpinBoxImageWindow.setDecimals(10)
        self.doubleSpinBoxImageWindow.setMaximum(32767.0)
        self.doubleSpinBoxImageWindow.setProperty("value", 1.0)
        self.doubleSpinBoxImageWindow.setObjectName("doubleSpinBoxImageWindow")
        self.labelImageWindow = QtWidgets.QLabel(self.centralWidget)
        self.labelImageWindow.setGeometry(QtCore.QRect(246, 534, 40, 16))
        self.labelImageWindow.setObjectName("labelImageWindow")
        self.doubleSpinBoxImageLevel = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBoxImageLevel.setGeometry(QtCore.QRect(287, 559, 81, 20))
        self.doubleSpinBoxImageLevel.setDecimals(10)
        self.doubleSpinBoxImageLevel.setMinimum(-32767.0)
        self.doubleSpinBoxImageLevel.setMaximum(32767.0)
        self.doubleSpinBoxImageLevel.setObjectName("doubleSpinBoxImageLevel")
        self.labelImageLevel = QtWidgets.QLabel(self.centralWidget)
        self.labelImageLevel.setGeometry(QtCore.QRect(253, 561, 29, 16))
        self.labelImageLevel.setObjectName("labelImageLevel")
        self.graphicsViewUncert = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsViewUncert.setGeometry(QtCore.QRect(530, 530, 512, 512))
        self.graphicsViewUncert.setObjectName("graphicsViewUncert")
        self.graphicsViewUncertOverlay = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsViewUncertOverlay.setGeometry(QtCore.QRect(1050, 530, 512, 512))
        self.graphicsViewUncertOverlay.setObjectName("graphicsViewUncertOverlay")
        self.labelSliceIndex = QtWidgets.QLabel(self.centralWidget)
        self.labelSliceIndex.setGeometry(QtCore.QRect(99, 535, 61, 16))
        self.labelSliceIndex.setObjectName("labelSliceIndex")
        self.doubleSpinBoxUncertLevel = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBoxUncertLevel.setGeometry(QtCore.QRect(429, 557, 81, 20))
        self.doubleSpinBoxUncertLevel.setDecimals(10)
        self.doubleSpinBoxUncertLevel.setMinimum(-32767.0)
        self.doubleSpinBoxUncertLevel.setMaximum(32767.0)
        self.doubleSpinBoxUncertLevel.setObjectName("doubleSpinBoxUncertLevel")
        self.doubleSpinBoxUncertWindow = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBoxUncertWindow.setGeometry(QtCore.QRect(431, 530, 81, 20))
        self.doubleSpinBoxUncertWindow.setDecimals(10)
        self.doubleSpinBoxUncertWindow.setMaximum(32767.0)
        self.doubleSpinBoxUncertWindow.setProperty("value", 1.0)
        self.doubleSpinBoxUncertWindow.setObjectName("doubleSpinBoxUncertWindow")
        self.labelUncertLabel = QtWidgets.QLabel(self.centralWidget)
        self.labelUncertLabel.setGeometry(QtCore.QRect(395, 559, 29, 16))
        self.labelUncertLabel.setObjectName("labelUncertLabel")
        self.labelUncertWindow = QtWidgets.QLabel(self.centralWidget)
        self.labelUncertWindow.setGeometry(QtCore.QRect(389, 532, 40, 16))
        self.labelUncertWindow.setObjectName("labelUncertWindow")
        self.doubleSpinBoxUncertAlpha = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBoxUncertAlpha.setGeometry(QtCore.QRect(429, 586, 81, 20))
        self.doubleSpinBoxUncertAlpha.setDecimals(1)
        self.doubleSpinBoxUncertAlpha.setMinimum(0.0)
        self.doubleSpinBoxUncertAlpha.setMaximum(1.0)
        self.doubleSpinBoxUncertAlpha.setSingleStep(0.1)
        self.doubleSpinBoxUncertAlpha.setObjectName("doubleSpinBoxUncertAlpha")
        self.labelUncertAlpha = QtWidgets.QLabel(self.centralWidget)
        self.labelUncertAlpha.setGeometry(QtCore.QRect(395, 586, 31, 20))
        self.labelUncertAlpha.setObjectName("labelUncertAlpha")
        self.doubleSpinBoxImageAlpha = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBoxImageAlpha.setGeometry(QtCore.QRect(287, 587, 81, 20))
        self.doubleSpinBoxImageAlpha.setDecimals(1)
        self.doubleSpinBoxImageAlpha.setMinimum(0.0)
        self.doubleSpinBoxImageAlpha.setMaximum(1.0)
        self.doubleSpinBoxImageAlpha.setSingleStep(0.1)
        self.doubleSpinBoxImageAlpha.setObjectName("doubleSpinBoxImageAlpha")
        self.labelImageAlpha = QtWidgets.QLabel(self.centralWidget)
        self.labelImageAlpha.setGeometry(QtCore.QRect(253, 586, 31, 20))
        self.labelImageAlpha.setObjectName("labelImageAlpha")
        self.spinBoxSliceIndex = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBoxSliceIndex.setGeometry(QtCore.QRect(162, 532, 61, 22))
        self.spinBoxSliceIndex.setObjectName("spinBoxSliceIndex")
        self.comboBoxSliceAxis = QtWidgets.QComboBox(self.centralWidget)
        self.comboBoxSliceAxis.setGeometry(QtCore.QRect(10, 530, 69, 22))
        self.comboBoxSliceAxis.setObjectName("comboBoxSliceAxis")
        self.comboBoxSliceAxis.addItem("")
        self.comboBoxSliceAxis.addItem("")
        self.comboBoxSliceAxis.addItem("")
        self.textBrowserShape = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowserShape.setGeometry(QtCore.QRect(8, 738, 251, 61))
        self.textBrowserShape.setAutoFillBackground(True)
        self.textBrowserShape.setObjectName("textBrowserShape")
        self.textBrowserScalar = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowserScalar.setGeometry(QtCore.QRect(8, 830, 251, 211))
        self.textBrowserScalar.setAutoFillBackground(True)
        self.textBrowserScalar.setObjectName("textBrowserScalar")
        self.labelShape = QtWidgets.QLabel(self.centralWidget)
        self.labelShape.setGeometry(QtCore.QRect(10, 720, 50, 12))
        self.labelShape.setObjectName("labelShape")
        self.labelScalar = QtWidgets.QLabel(self.centralWidget)
        self.labelScalar.setGeometry(QtCore.QRect(10, 810, 81, 16))
        self.labelScalar.setObjectName("labelScalar")
        AnatomyViewer.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(AnatomyViewer)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1570, 21))
        self.menuBar.setObjectName("menuBar")
        AnatomyViewer.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(AnatomyViewer)
        self.mainToolBar.setObjectName("mainToolBar")
        AnatomyViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(AnatomyViewer)
        self.statusBar.setObjectName("statusBar")
        AnatomyViewer.setStatusBar(self.statusBar)

        self.retranslateUi(AnatomyViewer)
        QtCore.QMetaObject.connectSlotsByName(AnatomyViewer)

    def retranslateUi(self, AnatomyViewer):
        _translate = QtCore.QCoreApplication.translate
        AnatomyViewer.setWindowTitle(_translate("AnatomyViewer", "AnatomyViewer"))
        self.labelImageWindow.setText(_translate("AnatomyViewer", "Window:"))
        self.labelImageLevel.setText(_translate("AnatomyViewer", "Level:"))
        self.labelSliceIndex.setText(_translate("AnatomyViewer", "Slice index:"))
        self.labelUncertLabel.setText(_translate("AnatomyViewer", "Level:"))
        self.labelUncertWindow.setText(_translate("AnatomyViewer", "Window:"))
        self.labelUncertAlpha.setText(_translate("AnatomyViewer", "Alpha:"))
        self.labelImageAlpha.setText(_translate("AnatomyViewer", "Alpha:"))
        self.comboBoxSliceAxis.setItemText(0, _translate("AnatomyViewer", "Axial"))
        self.comboBoxSliceAxis.setItemText(1, _translate("AnatomyViewer", "Sagittal"))
        self.comboBoxSliceAxis.setItemText(2, _translate("AnatomyViewer", "Coronal"))
        self.labelShape.setText(_translate("AnatomyViewer", "Shape:"))
        self.labelScalar.setText(_translate("AnatomyViewer", "Scalar:"))
